#!/usr/bin/env bash
# Init script to set up the symlinks for the config files
# Usage: ./init

CURRENTDIR="$(pwd)"
HOMEDIR=/Users/oliviac

echo "Changing to the ${CURRENTDIR} directory"
cd "${CURRENTDIR}" || exit


# create symlinks for all files in symlinks directory
create_symlinks() {
  for file in "${CURRENTDIR}/symlinks"/*; do
    local filename
    filename="$(basename "${file}")"

    echo "Creating a symlink to $filename in home directory"
     [[ -r ${file} ]] && [[ -e ${file} ]] && rm -f "${HOMEDIR}/.${filename}" && ln -s "${file}" "${HOMEDIR}/.${filename}"
  done

  # spaceship prompt config
  ln -sf "${CURRENTDIR}/config/starship.toml" "${HOMEDIR}/.config/starship.toml"
}

create_symlinks

unset create_symlinks
