[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[terminal]

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#505050"
blue = "#6fc2ef"
cyan = "#12cfc0"
green = "#acc267"
magenta = "#e1a3ee"
red = "#fb9fb1"
white = "#f5f5f5"
yellow = "#ddb26f"

[colors.cursor]
cursor = "#d0d0d0"
text = "#151515"

[colors.normal]
black = "#151515"
blue = "#6fc2ef"
cyan = "#12cfc0"
green = "#acc267"
magenta = "#e1a3ee"
red = "#fb9fb1"
white = "#d0d0d0"
yellow = "#ddb26f"

[colors.primary]
background = "#151515"
foreground = "#d0d0d0"

[font]
normal = { family = "MonoLisa" }
size = 12

[terminal.shell]
args = ["--login"]
program = "/bin/bash"

[window]
startup_mode = "Maximized"

[window.padding]
x = 5
y = 2

[keyboard]
