if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

. "$HOME/.cargo/env"

export PATH="$PATH:/Users/oliviac/.local/bin"


# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/oliviac/Library/Application Support/Herd/config/php/83/"


# Herd injected PHP binary.
export PATH="/Users/oliviac/Library/Application Support/Herd/bin/":$PATH


# Herd injected PHP binary.
export PATH="/Users/oliviac/Library/Application Support/Herd/bin/":$PATH
