if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

. "$HOME/.cargo/env"

export PATH="$PATH:/Users/oliviac/.local/bin"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/oliviac/google-cloud-sdk/path.bash.inc' ]; then . '/Users/oliviac/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/oliviac/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/oliviac/google-cloud-sdk/completion.bash.inc'; fi
