export PATH=/usr/local/bin:/usr/local/sbin:${PATH}
export PATH="/usr/local/opt:$PATH"
# add python v3 to path
# add folder containing custom bash scripts to path
export PATH="$HOME/projects/bash_scripts:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

# use GNU version of sed
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

export GOPATH="/Users/oliviacoumans/go"

export EDITOR='nvim'

source_config_files() {
  local homedir=/Users/oliviacoumans
  local dotfilesdir="${homedir}/dotfiles"

  shopt -s nullglob
  for file in "${dotfilesdir}/sources/"*; do
    [[ -r ${file} ]] && [[ -f ${file} ]] && source "${file}"
  done
  shopt -u nullglob
}

source_config_files
unset -f source_config_files

# for signed commit
export GPG_TTY=$(tty)

# remove warning when first log into shell
export BASH_SILENCE_DEPRECATION_WARNING=1

# tell fzf to use extended regex option
export FZF_DEFAULT_OPTS="--extended"

# make sure fzf respects .gitignore in fuzzy find
export FZF_DEFAULT_COMMAND="fd --type f"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --no-ignore-vcs --ignore -g "!{node_modules,.git}" '

# add fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# add spaceship prompt
eval "$(starship init bash)"

# add git autocomplete
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# pnpm
export PNPM_HOME="/Users/oliviac/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end
. "$HOME/.cargo/env"

TERM="xterm"
export TERM

export KERL_CONFIGURE_OPTIONS="--without-javac"
export KERL_BUILD_DOCS=no
