#!/usr/bin/env bash

# File containing git helper functions
# Usage in gitconfig file in the alias section

HASH="%C(always,yellow)%h%C(always,reset)"
RELATIVE_TIME="%C(always, green)%ar%C(always,reset)"
AUTHOR="%C(always,blue)%an%C(always,reset)"
REFS="%C(always,red)%d%C(always,reset)"
SUBJECT="%s"
FORMAT="$HASH{$RELATIVE_TIME{$AUTHOR{$REFS $SUBJECT"

# Format git print log nicely
# Source: https://www.destroyallsoftware.com/screencasts/catalog/pretty-git-logs
# Official doc: https://www.git-scm.com/docs/git-log#_commit_formatting
pretty_git_log() {
  git log --graph --pretty="tformat:$FORMAT" $* |
  column -t -s '{' |
  less -FXRS
}
